// Seed article. House rule: the claim is true and sourced; the joke lives
// inside the true part. The memoir is the source. The peach emoji is his.

export const articles24 = [
{
  title: 'Dylan Trussell',
  ratings: { helpful: [88, 9], funny: [241, 14] },
  revisions: [
    { user: 'Ornithopod', daysAgo: 6, comment: 'created article', content: `'''Dylan Trussell''' co-founded Culprit Underwear and wrote a book about it. The book has a discount code.

== References ==
{{reflist}}
` },
    { user: 'HansardHannah', daysAgo: 4, comment: 'expanded from his book, Forbes, Amazon, Apparel News, and the Airplane Mode record', content: `{{true and funny|source=Dylan Trussell, The Shortcut (Culprit Press, 2026)}}
{{Infobox
| title = Dylan Trussell
| occupations = Commercial director, entrepreneur, author
| known for = Culprit Creative, Culprit Underwear, ''The Shortcut''
| notable works = ''The Shortcut: How to Start Your Brand with Zero Experience'' (2026)
| companies = Culprit Creative; Culprit Underwear
| education = University of Colorado Boulder (no degree)
| father = Vance
| website = cheatcodesforlyfe.substack.com
}}

'''Dylan Trussell''' is a college dropout who writes that he has spoken at Harvard Business School, a Forbes 30 Under 30 honoree whose 2014 listing spelled him Dylan Trussel, and the co-founder of an underwear company that, by his own account, made two million dollars and then five million dollars of debt.<ref name="intro">Dylan Trussell, ''The Shortcut: How to Start Your Brand with Zero Experience'' (Culprit Press, 2026), Introduction. "I'm a college dropout. But I've spoken at Harvard Business School." "Our first year, my brilliance made us two million dollars. Two years later, that same brilliance got us into five million dollars of debt."</ref><ref name="forbeslist">Emily Cappiello, "2014 30 Under 30: Marketing & Advertising," ''Forbes'', 3 December 2013. The slide is headed "Colt Seman, 28, David Dinetz, 26, Dylan Trussel, 26" and calls them founders of Culprit Creative. https://www.forbes.com/pictures/54f4e707da47a54de82448fb/colt-seman-28-david-dinet/</ref><ref name="forbes">''Forbes'' profile, "Dylan Trussell," cofounder, Culprit Creative, last updated 1 January 2014. The profile spells the surname with two L's. https://www.forbes.com/profile/dylan-trussell/</ref>

He is the author of ''The Shortcut: How to Start Your Brand with Zero Experience'', a business book he began on the shoulder of the road, in a 1962 Lincoln Continental with five ashtrays and no seatbelts, after a lender called.<ref name="ch1">Trussell, ''The Shortcut'', ch. 1, "Let Your Anger Fuel You."</ref> The page before the introduction is headed "How to Start Your Brand…" The next line is "Step one: Don't."<ref name="front">Trussell, ''The Shortcut'', front matter, before the Introduction.</ref>

== Early life ==
The book does not give a birth date or a birthplace. It does give the delivery. In the acknowledgments he thanks his father, Vance, "for delivering me into this world before a doctor could get there, and for teaching me math on a McDonald's napkin."<ref name="acks">Trussell, ''The Shortcut'', Acknowledgments.</ref> Vance later worked as a lighting director. Trussell writes that his father designed the glowing briefcase in ''Pulp Fiction'', and that when Vance asked Quentin Tarantino what was in it, Tarantino said, "No one ever knows what's in the fuckin' briefcase."<ref name="ch63">Trussell, ''The Shortcut'', ch. 63, "Be Memorable."</ref>

In fifth grade, he writes, a boy he calls his best friend polled all sixty kids in the grade on who was the bigger loser. The vote was unanimous. Trussell sobbed. He had forgotten it, he says, until he wrote the chapter, and he was not ready to thank the boy, because he still wanted the fuel. The same friend now writes him on Instagram for business advice. Trussell's considered reply is thirty dollars, so the friend can buy the book.<ref name="ch9">Trussell, ''The Shortcut'', ch. 9, "Deal with Your Shit."</ref>

In tenth grade his grades slipped. His mother made him take Adderall in front of her. The grades rose and the jokes died. He describes the result as a smug, methed-out know-it-all whose friends left the table when he sat down. He started spitting the pills out. The friends came back. The A's went back to C's. "C's get degrees," he writes. He does not have the degree.<ref name="ch15">Trussell, ''The Shortcut'', ch. 15, "The Advantage of a Disadvantage."</ref><ref name="ch4">Trussell, ''The Shortcut'', ch. 4, "How to Think."</ref>

He got twelve rejection letters and one acceptance, from the University of Colorado Boulder, a safety school he had not visited. On the first day he met David Dinetz, his future business partner. Within the year he had decided to direct movies.<ref name="ch15" /> ''Forbes'' later described Trussell as Dinetz's creative partner since college.<ref name="forbes" /> He calls himself, in different chapters, a college dropout and a film-school dropout.<ref name="intro" /><ref name="ch22">Trussell, ''The Shortcut'', ch. 22, "Have a Mentor." "I'm a film school dropout."</ref> He also writes that he photoshopped his degree.<ref name="ch4" />

His mother, he writes, went broke across his high-school and college years and lost the house. He remembers her on the phone with American Express, and letters from law firms that he still sees as "Amex Vs. Gwen." At 3 a.m., after a shift at a nightclub, she asked him to salvage what he could. He stuffed a banged-up 1997 Lincoln and drove off. His grandfather had left him a beat-up 1997 Lincoln Town Car. He writes that his credit was never better than the day before he started his own brand.<ref name="ch9" /><ref name="ch70">Trussell, ''The Shortcut'', ch. 70, "It's Supposed to be Hard."</ref>

The other Lincoln is the 1962 Continental convertible. It has no seatbelts. It has five ashtrays. He was sitting in it, too angry to drive, when the book started.<ref name="ch1" />

== Culprit Creative ==
In 2014 he had just started the production company Culprit Creative. The work he lists from that life includes commercials for Starbucks, what he calls launching "the Stories feature for Instagram," a spot on what he calls the largest billboard in America for Beats by Dre, and shoots for Virgin Atlantic, Spotify, Coca-Cola, and a Super Bowl ad for Mercedes. The line sits in a list of commercials and campaigns.<ref name="intro" /><ref name="ch118">Trussell, ''The Shortcut'', ch. 118, "Keep the Champagne on Ice."</ref> ''Forbes'', writing the company up for the 2014 list, named different clients: King, the maker of Candy Crush, and Legendary Pictures, and said the agency was pitching Tesla. The same profile says Trussell had directed commercials for ESPN and Mattel.<ref name="forbes" /> The 30 Under 30 slide gives three founders and three ages: Colt Seman, 28; David Dinetz, 26; Dylan Trussel, 26. Seman is a cinematographer. The list is dated 3 December 2013.<ref name="forbeslist" /> Seman is credited as cinematographer on the feature they eventually made.<ref name="wikiplane">"Airplane Mode (2019 film)," ''Wikipedia''. Directed by David Dinetz and Dylan Trussell. Cinematography by Colt Seman. Production company Culprit Creative. Mammoth Film Festival, February 2019; released 2 August 2019. The lawsuit section, citing Complex, the ''International Business Times'', ''People'', and Yahoo Entertainment, says Planeless Pictures sued Logan Paul in December 2020 for upwards of $3 million and that the suit settled in May 2024. https://en.wikipedia.org/wiki/Airplane_Mode_(2019_film)</ref>

Trussell's own account of the honor puts it in a list. "Like many other young visionaries—and future criminals, such as Martin Shkreli, Sam Bankman-Fried, and Elizabeth Holmes—we were honored by Forbes on their annual 30 Under 30 list."<ref name="ch118" />

They wanted a brand to pay for Sundance. A startup underwear company liked an idea about people skiing in their underwear. ''The Wolf of Wall Street'' had just come out, so they made ''The Wolf of Sundance''. Trussell and Dinetz took turns in a wolf mask. Trussell took his clothes off on a celebrity red carpet and was dragged out by security yelling, "I've been kicked out of nicer places than this!" They then spent a month on the next pitch. The chief marketing officer said he did not know if it was on brand, and asked if they could film a guy pushing a girl on a skateboard on Venice Boardwalk. In the parking lot Trussell said, "Fuck them! We're starting our own underwear brand." Dinetz was unsure. Trussell said, "Culprit Underwear." Dinetz liked the name. Trussell said, "Get caught with your pants down." Dinetz said he saw it.<ref name="ch1" />

Before any of that paid off, a Toyota commercial had been refused because they had never shot a car commercial. They made a spec for the Tesla Model S instead. They talked their way into a studio and a car turntable. A Tesla-coil company in Texas overnighted a coil that cost the owner $10,000 to ship, because the owner liked Teslas. The technician said twelve feet was the death zone, past which the coil would "liquify our heart." They marked twelve feet in chalk. The car was inside the chalk, and lightning hit it until the screens turned on. Vance did the lighting in exchange for an In-N-Out burger. Five people, one camera, and a budget Trussell puts at $167, hotel and burgers included. He writes that the spec is what later helped them book the Mercedes Super Bowl ad.<ref name="ch46">Trussell, ''The Shortcut'', ch. 46, "Have a Bias for Action."</ref>

The pitches that did not sell are in the book with the props still attached. For a series about the bank robber who inspired ''Point Break'', they carried the outline in the ''Pulp Fiction'' briefcase and never opened it. For a cryogenics show, they carried a metal case he spells Haliburton, full of dry ice, weapons, and a script frozen in a block of ice, into a meeting at J. J. Abrams's company, Bad Robot, after telling a security guard they could not open it because it was frozen. An executive picked a weapon and hacked the script out. Trussell writes that they called it the best pitch they had ever gotten. "Didn't sell that show either. Hollywood is hard."<ref name="ch63" />

At twenty-four, the night before his first big pitch at Fox Studios, he liked the way two glasses of white wine had gone in rehearsal. At 8 a.m. he stopped at Starbucks, took three to-go cups, and split a bottle of Chardonnay among the three people pitching. They drank it in the room. He writes that the executives laughed.<ref name="ch67">Trussell, ''The Shortcut'', ch. 67, "Pitching Your Product."</ref>

He describes Dinetz as the person who has kept him employable. "Sense beaten into me with harsh words and the occasional physical violence," "lovingly applied," is his phrasing, and he says they have come to physical blows on several occasions. He calls him a saintly-patient partner of two decades and thanks him.<ref name="ch27">Trussell, ''The Shortcut'', ch. 27, "Find Someone Who Believes in You."</ref><ref name="ch28">Trussell, ''The Shortcut'', ch. 28, "Find the Right Co-Founder."</ref> The acknowledgments call him "my platonic life and business partner."<ref name="acks" />

== Culprit Underwear ==
''California Apparel News'' reported in March 2021 that the two filmmakers had started the underwear brand in 2019 as a side hustle, while a scripted comedy called ''Florida Man'' was heading into production, and that the COVID-19 shutdown gave them the time. The paper said Trussell was the fit model. A 2019 beta, black, with the logo on the waistband, sold out in a month, Dinetz told the paper. They estimated the customers had gone from 95 percent men to 70 percent women. About 95 percent of the fabric was modal. One print, the Pig Short, was about the GameStop trade, and the paper said the proceeds were going into GameStop shares.<ref name="apparel">Andrew Asch, "Culprit Underwear Approaches Sustainability With a Touch of Humor," ''California Apparel News'', 4 March 2021. https://www.apparelnews.net/news/2021/mar/04/culprit-underwear-approaches-sustainability-touch-/</ref> The book dates the public launch to April 2020 and says the videos had been viewed over 300 million times, which is his figure.<ref name="ch3">Trussell, ''The Shortcut'', ch. 3, "Think Bigger."</ref> The Better Business Bureau's file on Culprit Underwear, LLC, in South Pasadena, lists the business as started on 19 October 2016, which is earlier than the side hustle in ''Apparel News'' and earlier than the April 2020 launch in the book. The file lists Trussell as chief executive and Dinetz as founder. It also lists BAEthing suits and socks, the two categories he later told readers not to make.<ref name="bbb">Better Business Bureau, Culprit Underwear, LLC, South Pasadena, file opened 31 August 2020. Business started 19 October 2016. Management: Dylan Trussell, CEO; David Dinetz, founder. Rating D−, "Failure to respond to 14 complaint(s)." Products include BAEthing Suits and Socks. https://www.bbb.org/us/ca/south-pasadena/profile/online-retailer/culprit-underwear-llc-1216-1285756</ref>

The revenue, all of it from the book, runs like this. The first year, two million dollars. The next year he thought they could do eight million, ordered 3,000 yards of fabric, then 8,000 they could not afford, then 13,000 more before the 8,000 had arrived, and hit eight million. He writes that he was "pulling these numbers straight outta my 🍑" and that those particular numbers were right. He then planned a thirty-million-dollar year, added swimwear, socks, and workout shorts, and did not grow. A later chapter puts the same miss in calendar time: purchase orders sized for twenty million in underwear and ten million in the new products, and "instead of $30 million in 2022, we did less than $9 million," which "put us $5 million in debt." Another chapter puts the eight million at the close of 2021, "our second year of business."<ref name="intro" /><ref name="ch72">Trussell, ''The Shortcut'', ch. 72, "Sit Shotgun, Let Your Ego Drive."</ref><ref name="ch93">Trussell, ''The Shortcut'', ch. 93, "Slow Is Fast."</ref><ref name="ch89">Trussell, ''The Shortcut'', ch. 89, "Never Have a Single Point of Failure."</ref> The thirty million dollars he mentions in the Lincoln is a different thirty million. While a lender was threatening a UCC hold that would freeze Shopify, he wrote that the company was "currently valued at over $30 million." He does not show the valuation. He names the lender, says he probably cannot name them legally, and names them anyway. "It's Ampla. And in my humble opinion, they're predatory pieces of shit."<ref name="ch1" />

The swimwear gets its own chapter, which is chapter 86, "Don't Make Swimwear." In the ego chapter he tells the reader the story is in chapter 85. Chapter 85 is "Stay in Your Lane."<ref name="ch72" /><ref name="ch86">Trussell, ''The Shortcut'', ch. 86, "Don't Make Swimwear."</ref> They ordered half a million dollars of swimwear and took on a million dollars of debt to make and market it. It was ready in July. He writes that swim season starts in January and ends in June. The suits were $99, which he says was a third of Vilebrequin. The women's suit was men's trunks, named the BAEthing suit. The men's suit had a removable liner. "It was a bulletproof plan." The next sentence is that no one cared. The women's suits sold for two months and sat for eight. The men's trunks were still in the warehouse two years later. "Our ad was so funny, I cried…all the way to the empty bank." The chapter's instruction is in capitals. "DO NOT EXPAND YOUR PRODUCT LINE." The last line of the lesson is that you can do more in life than marginally improve how people look at the beach.<ref name="ch86" /> The socks, sold in threes instead of pairs, were still in stock when he wrote the testing chapter. "Test before you invest."<ref name="ch51">Trussell, ''The Shortcut'', ch. 51, "Test the Market."</ref>

To fund the stall he pulled a two-million-dollar credit line at 17 percent, put a million dollars on credit cards at 28 percent, and put in every dollar he had personally accumulated. At the time of one sentence he was still paying the credit line down, from two million to fifty thousand.<ref name="ch72" /> When he typed the first page he owed Ampla $300,000. At the sentence where he paid them off, the last transfer was six thousand dollars. He answered their confirmation email with the "It's Done" image of Frodo from ''The Lord of the Rings'', and he was in a cold plunge, playing Ice Cube's "Good Day," with palo santo in the air.<ref name="ch102">Trussell, ''The Shortcut'', ch. 102, "Always Have a Buffer."</ref>

A Sunset billboard cost $10,000 for a week. They put no discount code on it, so they could not trace a sale, and he doubts the week made one. It was the height of COVID, other brands cut their budgets, and the board stayed up ten months. "We used to be really dumb. We still are, but we used to be also."<ref name="ch53">Trussell, ''The Shortcut'', ch. 53, "Trace Your Success."</ref>

The book includes a section in the voice of Tim Fox, whom Trussell presents as the first operations hire, a writer and actor he had met at a party and called when a restaurant closed. In that account a Reno warehouse holding the inventory locked its doors before Thanksgiving. Fox writes that he looked through a window at four million dollars of underwear and waited in a rental car to see if a door would open.<ref name="ch89" />

On 15 June 2025, more than a year after he had "finished" the book, he wrote that a WeFunder campaign was nearing $100,000 and would take at least thirty days, which was not soon enough to restock. He was selling the 1962 Lincoln, "my most prized possession," the car the book had started in.<ref name="ch113">Trussell, ''The Shortcut'', ch. 113, "Risky Business and the Business of Risk." The date in the chapter is 15 June 2025.</ref>

The car that did not survive the underwear business was a Ferrari. Chapter 118 says that when a movie deal seemed real, he and Dinetz bought a house in the hills and a 1997 Ferrari F355. Chapter 72 describes an F355 Spyder in Rosso Corsa, with 7,000 miles, bought, in that chapter's telling, from his years as a commercial director. He does not say he owned two. A neighbor, two houses away, was texting and driving. He writes "luckily" before he writes that she totaled it. She was unhurt, and sober, "which was the hardest part to believe." The insurer offered $80,000. A friend at a dealership he calls scummy told him to refuse it. He got to $100,000. The next day the fabric supplier called. The bill was $100,000. The money "disappeared into inventory purgatory." He wrote a poem about it. The neighbor had thrown them a bone by driving while on her phone.<ref name="ch72" /><ref name="ch118" />

== Airplane Mode ==
The film is called ''Airplane Mode''. Dinetz and Trussell directed it. Culprit Creative produced it. It premiered at the Mammoth Film Festival in February 2019 and was released on 2 August 2019.<ref name="wikiplane" /> The book tells the production without using the title. Trussell had rewatched the 1980 comedy ''Airplane!'' and wanted every social-media star of 2015 on one plane, playing themselves. He writes that they signed twenty-five of them, with a combined following of 600 million, each committed to three posts. Forty financing meetings, he writes, said yes to the idea and no to the terms, which were two million dollars and an R rating. He was on a date. She said her father used to make straight-to-video National Lampoon movies and had lost his money on the last one. Trussell asked for a meeting the next day. The father looked at a reel, showed it to his much younger girlfriend, and said, "She hates your idea…but she's an opposite indicator. Everything she likes sucks, so I'm in." A thirty-second meeting with a billionaire getting off a private plane closed the rest.<ref name="ch118" />

The script, by his count, had ninety-eight speaking roles, stunts, wire fights, a llama, and a baby. The producer said it could not be done for two million dollars. They raised another $500,000 by selling product placement to old clients and put in $50,000 of their own, which he calls the only money they had. They planned to shoot it in fifteen days, which he also calls three weeks. He writes that he went against union rules and tossed sandbags and equipment out of the room because the crew was moving too slowly. They hired an editor because the editor's father had done Oscar-winning movies. "The apple fell so far from the tree that it fermented." They never received their directing fees. A second editor's house became the edit bay, and they worked there every day for six months.<ref name="ch118" />

Then the sale. He writes that YouTube Originals bought a six-month exclusive for four million dollars, with iTunes and Netflix meant to follow, and that the movie was "set to make $10 million." The contract was signed. They opened the champagne. They bought the house and the Ferrari. They went to Thailand for New Year's. The movie was two weeks from coming out. A text asked what Logan Paul had done. Paul, the lead, had posted a video from a suicide forest in Japan. Trussell writes the call to YouTube as: "We're still good, right?" "No, we're not good. Your lead actor uploaded a dead body to our platform." They were not paid. He had told Dinetz he was happy they would never have to do marketing again. "It was like we won the lottery, spent the money, then lost the ticket." They called every old client, said they were booked solid except for the next two weeks, and offered 20 percent off. He writes that the month saved the house and booked the Mercedes Super Bowl commercial.<ref name="ch118" />

The released film, he writes, was re-edited, made more "appropriate," and less funny. "Still to this day, I've never watched it." News reports in December 2020 said the production company, Planeless Pictures, sued Paul for upwards of three million dollars, alleging the video had led Google to suspend an exclusive publishing deal. The suit was reported settled in May 2024. The book's four million dollars and the lawsuit's three million dollars are two different numbers, from him and from the coverage, and this article does not merge them.<ref name="ch118" /><ref name="wikiplane" />

== The Shortcut ==
The book started as a list. After the lender's call he pulled over in the Lincoln, skipped the gym, and wrote "the top ten things to know before you start your business." The sun went down. The list hit thirty. He decided it was a book. He went home and kept going. The spite, in his telling, is the method. "It's almost as if, In The Beginning…God said, 'Let there be spite'!"<ref name="ch1" />

He had listened, he writes, to all 360 episodes of David Senra's ''Founders'' podcast in a year, and most of the book is other people's lessons boiled down again. "Is most of this book just stuff I've heard, read, and regurgitated to you? In short, yes." He says the line about there being no original thoughts was stolen from Mark Twain, including the theft.<ref name="intro" /> He met Senra at an event in Miami, used a New York appearance as the deadline for a first draft, and handed him the opening hour on a cassette inside a 1979 Sony Walkman. One in working order was listed at $500. He bought two, because they were from 1979. One did not work. The request that Senra write the foreword was on side B. Trussell does not think Senra flipped the tape.<ref name="ch63" />

The history in the book is annotated, sometimes as history and sometimes as his. Alexander at the Gordian knot is one of the second kind. "I imagine it was a crisp fall day," he writes, with rotting apples and "squirrels were getting drunk off the fermented fruit," too drunk to care that Alexander had arrived. He is explicit that he is imagining it. He also imagines that Alexander did not stop to film them on an iPhone.<ref name="ch37">Trussell, ''The Shortcut'', ch. 37, "Cut The Gordian Knot."</ref>

Culprit Press published the paperback on 24 February 2026. Amazon lists 494 pages, ISBN 978-1544551043. The "About the Author" note on the product page calls him founder and chief mischief-maker of Culprit Underwear, says he was named to the Forbes 30 Under 30 list for marketing and advertising, and calls him a guest lecturer at Harvard Business School who never graduated from college. The book itself says he has spoken there.<ref name="amazon">Amazon.com product page for ''The Shortcut: How to Start Your Brand with Zero Experience'', paperback, ASIN 1544551045, ISBN-13 978-1544551043, publisher Culprit Press, publication date 24 February 2026, 494 pages. "About the Author" note on that page. https://www.amazon.com/Shortcut-Start-Your-Brand-Experience/dp/1544551045 Read 8 October 2026. The page ranked the book and did not display a bestseller banner. This article does not call it a bestseller.</ref><ref name="intro" /> The manuscript he circulated before the press run runs to 127 numbered chapters plus the front and back matter. He writes that he finished it, held it for a year because the company was in trouble, and published it anyway. The last pages plug Culprit, a snack line he calls Mortal Munchies, and hangover pills he calls Elxxr, "that actually work," which is his claim. "How's that for a plug?" The code printed there is Shortcut20, good, he says, for all three. Deleted chapters are pointed at myshortcut.co.<ref name="end">Trussell, ''The Shortcut'', "Almost the End, My Friends," after ch. 127, "Novice vs. Master."</ref>

== Other ventures ==
He writes a Substack called Cheat Codes for Lyfe. The publication describes itself as "Cheat codes for the game of life. Founder advice, plus the personal stuff." On 8 October 2026 the page said it had launched a month ago.<ref name="sub">Dylan Trussell, ''Cheat Codes for Lyfe'', Substack, https://cheatcodesforlyfe.substack.com/ Accessed 8 October 2026.</ref> Mortal Munchies and Elxxr appear in the book and, as of 8 October 2026, nowhere else this article could cite.<ref name="end" />

== Philosophy ==
The sentences he underlines are short. "There are no shortcuts in life. Except this book." "Ego isn't healthy, but it can make you wealthy." "If you don't send the elevator back down, the next generation has to take the stairs." Belief, he says at the end, comes before ability. The reader is the main character. He tells them to shut the book and do something.<ref name="front" /><ref name="ch72" /><ref name="ch126">Trussell, ''The Shortcut'', ch. 126, "Send the Elevator Back Down."</ref><ref name="ch127">Trussell, ''The Shortcut'', ch. 127, "Novice vs. Master," and the "Final Words" that follow it.</ref> The pain advice in the introduction is one word in parentheses. Alcohol.<ref name="intro" /> A reader who has just launched swimwear is told he is not their mother and will not hit them with a sandal or a belt, because they are too far away.<ref name="ch103">Trussell, ''The Shortcut'', ch. 103, "What to Do in a Drought."</ref>

Tim Cook appears as weather. "What if Tim Cook unleashes the next IOS update and your Return On Ad Spend (ROAS) goes down by 50 percent and stays there like mine did?" He writes that the company had been living on Facebook ads, that iOS 14 cut off the data, and that the channel stopped scaling. In a later chapter the blame for a late paycheck does not land on the economy or on "Tim Cook's iOS 14 update." It lands on the founder.<ref name="ch88">Trussell, ''The Shortcut'', ch. 88, "Avoid Problems Duh."</ref><ref name="ch89" /><ref name="ch103" />

== Controversies (self-inflicted) ==
He confesses the marketing in the same tone he confesses the swimwear.

When the brand was new and the five-star pile was a couple of hundred reviews, "we wrote 99 percent five-star reviews." The line he says they use now is "over 10,000 five-star reviews."<ref name="ch57">Trussell, ''The Shortcut'', ch. 57, "Direct Response Video Ads."</ref>

American ''Vogue'' cost too much, so they paid a tenth of the asking price for Ukrainian ''Vogue''. The quotes on the site and in the ads are, he writes, real, and really from ''Vogue'', and translated from Ukrainian, and paid for. "Nothing about this was organic. I am giving you the secret sauce here." He adds that the other press on the site later became organic, and that the ''Vogue'' quote did not.<ref name="ch61">Trussell, ''The Shortcut'', ch. 61, "Full Court Press."</ref>

The degree is in chapter 4, in a sentence aimed at himself: a man "who never graduated college, photoshopped his degree, and calls himself an entrepreneur, but never had an exit."<ref name="ch4" />

A fold-over tag on the underwear, approved from a factory photo taken in Guatemala, scratched. He had made 50,000. "I'll probably only lose 20,000 customers for life." The "probably" is his. He is estimating his own damage in the same paragraph as the mistake.<ref name="ch88" />

The Better Business Bureau has not accredited Culprit Underwear, LLC, and rates it D−. The reason the bureau prints is failure to respond to fourteen complaints. The article does not know what the complaints said. The bureau's product list does include the BAEthing suit.<ref name="bbb" />

Chapter 84 is by Dinetz, introduced by Trussell as a guest author. A client had not paid for a commercial. Dinetz had the delivery watermarked with DickButt at 90 percent opacity. The book describes DickButt as a dick with a dick, with a butt for a butt, and credits the cartoon to Jeffrey McQuirk. The client, who is not named, told them they would never work in that town again. They were paid in cash, Dinetz writes, $10,000 from a safe, and spent it at Coachella. Trussell's coda is that DickButt is now a weapon in the arsenal, and that you do not have to use him.<ref name="ch84">Trussell, ''The Shortcut'', ch. 84, "The No-Assholes Rule." The chapter is signed in the text by David Dinetz.</ref>

The champagne rule is the one he says he keeps. Do not open it until the check has cleared and the money is in a different account. He had already opened it.<ref name="ch118" />

== Personal life ==
He introduces himself as stubborn, disorganized, a drinker, gullible, too trusting, and bad at the details of his own life. "My memory works better for useless facts than the details of my own life." His ADHD, he writes, will remove him from a conversation that matters. He asks his own reflection whether an almost-forty man is going to be the chief executive of a fledgling underwear brand at forty-five. ''Forbes'' had his age at 26 on the December 2013 list. The book gives no birthday.<ref name="front" /><ref name="ch8">Trussell, ''The Shortcut'', ch. 8, "Be Your Own Best Friend."</ref><ref name="forbeslist" />

He thanks his mother for being his rock. He thanks his sister for being a funny rival who became a friend, and, in the same sentence, apologizes for peeing on her while she changed him and ruining an ice-skating outfit before a meet. He says he did not mean to.<ref name="acks" /> He thanks an editor named Holly and Eric Jorgenson. He thanks the people who told him he had potential, and he thanks the people who made him angry more.<ref name="acks" />

The about-the-author note calls him a lazy hard worker, brilliantly braindead, stubbornly open-minded, and seriously hilarious depending on who is asked. His creditors in 2022, the note says, might have answered differently. The author, by that note, had already overshared.<ref name="about">Trussell, ''The Shortcut'', "About the Author."</ref>

== Bibliography ==
* Trussell, Dylan. ''The Shortcut: How to Start Your Brand with Zero Experience''. Culprit Press, 24 February 2026. ISBN 978-1544551043. 127 chapters in the pre-press manuscript, plus front and back matter. Paperback, 494 pages.

== External links ==
* [https://cheatcodesforlyfe.substack.com/ Cheat Codes for Lyfe], his Substack
* [https://www.forbes.com/profile/dylan-trussell/ Forbes profile]

== References ==
{{reflist}}

[[Category:True but improbable]]
` },
    { user: '203.0.113.55', daysAgo: 2, comment: 'fixed', content: `'''DYLAN TRUSSELL INVENTED UNDERWEAR.'''

He also invented the discount code. Use SHORTCUT20 for 20% off the underwear, the snacks, the pills, and the Ferrari. Forbes agrees. Culprit is a charity.

SHIPPING IS FREE IF YOU CAN PROVE YOU TOTALED HIS CAR.

== References ==
{{reflist}}
` },
    { user: 'CiteOrDie', daysAgo: 2, comment: 'Reverted edits by [[Special:Contributions/203.0.113.55|203.0.113.55]] to last revision by HansardHannah. The code is in the book. The page is not a store. He did not invent underwear.', revert: 2 },
    { user: 'CiteOrDie', daysAgo: 1, minor: true, comment: 'copyedit: land the last line on his', patch: [['The author, by that note, had already overshared.', '"The author already overshared."']] },
  ],
  talk: { user: 'CiteOrDie', daysAgo: 1, content: `== The discount code ==

An anonymous editor replaced the article with a store. The code SHORTCUT20 is real. It is printed in the back of the book. If the book prints it, why did the revert take the coupon down? ~~~

: Because the book prints it as his plug, and the article already says so, with the chapter. The vandalism said he invented underwear, that Forbes agrees, and that the Ferrari is on sale. None of that is in the book. ''Forbes'' put Culprit Creative on the 2014 30 Under 30 list and spelled his name with one L. It did not appoint him the inventor of boxers. [[Witipedia:Be funny]] is the sentence that is true. A checkout page is a different website. [[User:HansardHannah|HansardHannah]] ([[User talk:HansardHannah|talk]]) 11:14, 7 October 2026 (UTC)

:: Agreed. Leave the peach emoji as he typed it. He said he pulled the yardage out of his ass, and he typed a peach. Do not upgrade the peach to a spreadsheet. [[User:CiteOrDie|CiteOrDie]] ([[User talk:CiteOrDie|talk]]) 16:02, 7 October 2026 (UTC)
` },
},
];
