#!/usr/bin/env node
/**
 * Generates seed.sql: users, pages, full revision histories, talk pages and
 * ratings. Run with `npm run seed` (remote) or `npm run seed:local`.
 *
 * SITE_NAME     rename the wiki everywhere (default Witipedia)
 * ADMIN_PASSWORD  password for the Admin account (random if unset, printed once)
 */
import { writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { hashPassword } from '../src/auth.js';
import { articles1 } from './seed/articles-1.mjs';
import { articles2 } from './seed/articles-2.mjs';
import { projectPages } from './seed/project.mjs';

const SITE = process.env.SITE_NAME || 'Witipedia';
const adminPassword = process.env.ADMIN_PASSWORD || randomBytes(9).toString('base64url');
const NOW = Math.floor(Date.now() / 1000);
const DAY = 86400;

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const sub = (s) => String(s).replace(/Witipedia/g, SITE);
const key = (ns, title) => `${ns}:${title.replace(/ /g, '_')}`;

const EDITORS = [
  ['Admin', 'sysop,bureaucrat', 1400, 200],
  ['HansardHannah', 'editor', 812, 190],
  ['Ornithopod', 'editor', 645, 175],
  ['CubeWatch', '', 318, 120],
  ['MonotremeMary', '', 274, 110],
  ['CiteOrDie', '', 196, 96],
  ['Thoenfan', '', 141, 80],
  ['PollWatcher', '', 88, 70],
  ['Skinnerbox', '', 63, 60],
  ['Anonyfish', '', 57, 55],
];

const out = [];
out.push('-- Generated by tools/build-seed.mjs. Do not edit by hand.');
out.push('DELETE FROM ratings; DELETE FROM watchlist; DELETE FROM logs; DELETE FROM revisions; DELETE FROM pages; DELETE FROM sessions; DELETE FROM users;');

const userIds = new Map();
let uid = 0;
for (const [name, groups, edits, ageDays] of EDITORS) {
  uid++;
  userIds.set(name, uid);
  const pw = await hashPassword(name === 'Admin' ? adminPassword : randomBytes(16).toString('base64url'));
  out.push(`INSERT INTO users (id,username,username_lc,password_hash,email,created_at,edit_count,groups) VALUES (${uid},${q(name)},${q(name.toLowerCase())},${q(pw)},NULL,${NOW - ageDays * DAY},${edits},${q(groups)});`);
  out.push(`INSERT INTO logs (type,action,user_text,target,comment,created_at) VALUES ('newusers','created an account',${q(name)},'','',${NOW - ageDays * DAY});`);
}

let pid = 0, rid = 0;
function addPage({ ns, title, protect = '', revisions }) {
  pid++;
  const myPid = pid;
  const created = NOW - revisions[0].daysAgo * DAY;
  let last = null;
  let lastContent = '';
  const revRows = [];
  const byIndex = [];
  for (const r of revisions) {
    rid++;
    let content;
    if (r.revert !== undefined) content = byIndex[r.revert - 1];
    else if (r.patch) {
      content = lastContent;
      for (const [from, to] of r.patch) content = content.split(from).join(to);
    } else content = r.content;
    content = sub(content);
    byIndex.push(content);
    lastContent = content;
    const t = NOW - r.daysAgo * DAY + ((rid * 7919) % 86400) - 43200;
    const uidOf = userIds.get(r.user) ?? null;
    const tags = [revRows.length === 0 ? 'new' : '', r.revert !== undefined ? 'rollback' : ''].filter(Boolean).join(',');
    revRows.push(`INSERT INTO revisions (id,page_id,parent_id,user_id,user_text,comment,content,len,is_minor,tags,created_at) VALUES (${rid},${myPid},${last ?? 'NULL'},${uidOf ?? 'NULL'},${q(r.user)},${q(sub(r.comment || ''))},${q(content)},${content.length},${r.minor ? 1 : 0},${q(tags)},${t});`);
    last = rid;
  }
  const redirect = /^\s*#REDIRECT\s*:?\s*\[\[([^[\]|]+)/i.exec(lastContent);
  out.push(`INSERT INTO pages (id,namespace,title,page_key,current_rev_id,is_redirect,redirect_target,protect_edit,created_at,touched_at,len) VALUES (${myPid},${ns},${q(sub(title))},${q(key(ns, sub(title)))},${last},${redirect ? 1 : 0},${redirect ? q(sub(redirect[1])) : 'NULL'},${q(protect)},${created},${NOW - revisions[revisions.length - 1].daysAgo * DAY},${lastContent.length});`);
  out.push(...revRows);
  if (protect) {
    out.push(`INSERT INTO logs (type,action,user_text,target,comment,created_at) VALUES ('protect',${q(`protected (${protect})`)},'Admin',${q(sub(title))},'high-visibility page',${created});`);
  }
  return myPid;
}

// ---- articles, their talk pages and their ratings
const articles = [...articles1, ...articles2];
for (const a of articles) {
  const id = addPage({ ns: 0, title: a.title, protect: a.protect || '', revisions: a.revisions });
  if (a.talk) {
    addPage({ ns: 1, title: a.title, revisions: [{ user: a.talk.user, daysAgo: a.talk.daysAgo, comment: 'new section', content: a.talk.content }] });
  }
  for (const [axis, [up, down]] of Object.entries(a.ratings || {})) {
    // Real rows, so that toggling a vote and the per-person limit both behave.
    const rows = [];
    for (let i = 0; i < up; i++) rows.push(`(${id},'seed:${axis}:u${i}',${q(axis)},1,${NOW - (i % 60) * 3600})`);
    for (let i = 0; i < down; i++) rows.push(`(${id},'seed:${axis}:d${i}',${q(axis)},-1,${NOW - (i % 60) * 3600})`);
    for (let i = 0; i < rows.length; i += 200) {
      out.push(`INSERT INTO ratings (page_id,voter_key,axis,value,created_at) VALUES ${rows.slice(i, i + 200).join(',')};`);
    }
    const cols = axis === 'funny' ? ['rating_funny_up', 'rating_funny_down'] : ['rating_helpful_up', 'rating_helpful_down'];
    out.push(`UPDATE pages SET ${cols[0]}=${up}, ${cols[1]}=${down} WHERE id=${id};`);
  }
}

// ---- project, help, category and user pages
for (const p of projectPages) {
  addPage({
    ns: p.ns, title: p.title, protect: p.protect || '',
    revisions: [{ user: p.user, daysAgo: p.daysAgo, comment: p.comment, content: p.content }],
  });
}

// ---- a couple of redirects, because a real wiki has hundreds
for (const [from, to] of [['Emu War', 'Great Emu War'], ['Water bear', 'Tardigrade'], ['Peacock mantis shrimp', 'Mantis shrimp'], ['Five pillars', `${SITE}:Five pillars`]]) {
  addPage({ ns: 0, title: from, revisions: [{ user: 'Ornithopod', daysAgo: 30, comment: 'redirect', content: `#REDIRECT [[${to}]]` }] });
}

// ---- watchlist entries for the admin, so Special:Watchlist is not empty
out.push(`INSERT INTO watchlist (user_id,page_id) SELECT 1, id FROM pages WHERE namespace=0 AND is_redirect=0;`);

writeFileSync(new URL('../seed.sql', import.meta.url), `${out.join('\n')}\n`);
console.log(`seed.sql written: ${out.length} statements, site name "${SITE}"`);
if (!process.env.ADMIN_PASSWORD) {
  console.log(`\n  Admin login:  Admin / ${adminPassword}`);
  console.log('  (set ADMIN_PASSWORD before seeding to choose your own)\n');
}
